# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890 -Djdk.tls.keyAgreement=X25519,secp256r1 -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3 --enable-native-access=ALL-UNNAMED
org.gradle.java.home=G\:/jdk-25/jdk-25.0.3+9

# Proxy settings
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.socksProxyHost=127.0.0.1
systemProp.socksProxyPort=7890
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3

#Fabric api
fabric_version=0.154.2+26.2
# Mod Properties
mod_version=0.0.5-pre-alpha
maven_group=me.cortex
archives_base_name=vulkanite
